// ─── Mock Data for Dashboard — Stage 3 ───────────────────────────────────────
// All data is static and used only for UI demonstration purposes.
// No backend calls are made from this file.

// ── KPI Cards ─────────────────────────────────────────────────────────────────
export const kpiData = [
  {
    id: 'total-vendors',
    title: 'Total Vendors',
    value: 284,
    change: 12.5,
    trend: 'up' as const,
    icon: 'Users',
    color: 'blue',
    description: 'Active vendor relationships',
  },
  {
    id: 'active-rfqs',
    title: 'Active RFQs',
    value: 47,
    change: 8.2,
    trend: 'up' as const,
    icon: 'FileText',
    color: 'purple',
    description: 'Requests for quotation in progress',
  },
  {
    id: 'purchase-orders',
    title: 'Purchase Orders',
    value: 1243,
    change: -3.1,
    trend: 'down' as const,
    icon: 'ShoppingCart',
    color: 'green',
    description: 'Orders placed this quarter',
  },
  {
    id: 'pending-approvals',
    title: 'Pending Approvals',
    value: 18,
    change: 22.4,
    trend: 'up' as const,
    icon: 'Clock',
    color: 'orange',
    description: 'Items awaiting review',
  },
  {
    id: 'monthly-spend',
    title: 'Monthly Spend',
    value: 842500,
    change: 5.7,
    trend: 'up' as const,
    icon: 'DollarSign',
    color: 'cyan',
    description: 'Total procurement spend',
    isCurrency: true,
  },
  {
    id: 'inventory-alerts',
    title: 'Inventory Alerts',
    value: 9,
    change: -15.0,
    trend: 'down' as const,
    icon: 'AlertTriangle',
    color: 'red',
    description: 'Items below reorder point',
  },
]

// ── Procurement Spend — Bar Chart ─────────────────────────────────────────────
export const procurementSpendData = [
  { month: 'Jan', electronics: 120000, materials: 85000, services: 45000, logistics: 32000 },
  { month: 'Feb', electronics: 98000,  materials: 92000, services: 52000, logistics: 28000 },
  { month: 'Mar', electronics: 145000, materials: 78000, services: 48000, logistics: 35000 },
  { month: 'Apr', electronics: 132000, materials: 105000, services: 61000, logistics: 41000 },
  { month: 'May', electronics: 158000, materials: 118000, services: 55000, logistics: 38000 },
  { month: 'Jun', electronics: 172000, materials: 125000, services: 67000, logistics: 44000 },
  { month: 'Jul', electronics: 161000, materials: 112000, services: 59000, logistics: 40000 },
  { month: 'Aug', electronics: 189000, materials: 134000, services: 71000, logistics: 47000 },
]

// ── Monthly Purchase Trend — Line Chart ───────────────────────────────────────
export const purchaseTrendData = [
  { month: 'Jan', orders: 145, spend: 380000, budget: 400000 },
  { month: 'Feb', orders: 132, spend: 270000, budget: 400000 },
  { month: 'Mar', orders: 167, spend: 306000, budget: 420000 },
  { month: 'Apr', orders: 184, spend: 339000, budget: 420000 },
  { month: 'May', orders: 196, spend: 369000, budget: 450000 },
  { month: 'Jun', orders: 221, spend: 441000, budget: 450000 },
  { month: 'Jul', orders: 209, spend: 372000, budget: 470000 },
  { month: 'Aug', orders: 243, spend: 441000, budget: 470000 },
]

// ── Vendor Categories — Pie Chart ─────────────────────────────────────────────
export const vendorCategoriesData = [
  { name: 'Electronics',   value: 34, color: '#4350ed' },
  { name: 'Materials',     value: 26, color: '#8b5cf6' },
  { name: 'Services',      value: 18, color: '#22c55e' },
  { name: 'Logistics',     value: 12, color: '#f59e0b' },
  { name: 'IT & Software', value: 10, color: '#ef4444' },
]

// ── RFQ Status — Donut Chart ──────────────────────────────────────────────────
export const rfqStatusData = [
  { name: 'Open',      value: 18, color: '#4350ed' },
  { name: 'Reviewing', value: 12, color: '#8b5cf6' },
  { name: 'Awarded',   value: 9,  color: '#22c55e' },
  { name: 'Closed',    value: 5,  color: '#94a3b8' },
  { name: 'Cancelled', value: 3,  color: '#ef4444' },
]

// ── Recent Activity ───────────────────────────────────────────────────────────
export const recentActivityData = [
  {
    id: 'act-1',
    type: 'vendor_added',
    title: 'New vendor onboarded',
    description: 'TechSupply Co. has been verified and added to the platform.',
    time: '2 minutes ago',
    icon: 'UserPlus',
    color: 'blue',
  },
  {
    id: 'act-2',
    type: 'rfq_created',
    title: 'RFQ #RFQ-2024-0847 created',
    description: 'New request for 500 units of industrial sensors.',
    time: '28 minutes ago',
    icon: 'FileText',
    color: 'purple',
  },
  {
    id: 'act-3',
    type: 'po_approved',
    title: 'Purchase Order #PO-2024-1123 approved',
    description: '$48,500 order from ElectroComponents Ltd. has been approved.',
    time: '1 hour ago',
    icon: 'CheckCircle',
    color: 'green',
  },
  {
    id: 'act-4',
    type: 'invoice_paid',
    title: 'Invoice #INV-8841 paid',
    description: 'Payment of $12,750 processed to Global Materials Inc.',
    time: '3 hours ago',
    icon: 'DollarSign',
    color: 'cyan',
  },
  {
    id: 'act-5',
    type: 'inventory_updated',
    title: 'Inventory updated',
    description: 'Warehouse A: 1,200 units of Component XB-44 restocked.',
    time: '5 hours ago',
    icon: 'Package',
    color: 'orange',
  },
  {
    id: 'act-6',
    type: 'alert',
    title: 'Low stock alert',
    description: 'Fastener Kit FT-200 is below the reorder threshold.',
    time: '7 hours ago',
    icon: 'AlertTriangle',
    color: 'red',
  },
]

// ── Recent Vendors Table ───────────────────────────────────────────────────────
export const recentVendorsData = [
  {
    id: 'v-001',
    name: 'TechSupply Co.',
    logo: 'TS',
    category: 'Electronics',
    status: 'active',
    rating: 4.8,
    joinedDate: '2024-08-01',
    location: 'San Francisco, CA',
  },
  {
    id: 'v-002',
    name: 'Global Materials Inc.',
    logo: 'GM',
    category: 'Materials',
    status: 'active',
    rating: 4.5,
    joinedDate: '2024-07-22',
    location: 'Chicago, IL',
  },
  {
    id: 'v-003',
    name: 'ElectroComponents Ltd.',
    logo: 'EC',
    category: 'Electronics',
    status: 'active',
    rating: 4.2,
    joinedDate: '2024-07-15',
    location: 'Austin, TX',
  },
  {
    id: 'v-004',
    name: 'Swift Logistics',
    logo: 'SL',
    category: 'Logistics',
    status: 'pending',
    rating: 3.9,
    joinedDate: '2024-08-05',
    location: 'Atlanta, GA',
  },
  {
    id: 'v-005',
    name: 'ProServices Group',
    logo: 'PS',
    category: 'Services',
    status: 'active',
    rating: 4.6,
    joinedDate: '2024-06-30',
    location: 'New York, NY',
  },
  {
    id: 'v-006',
    name: 'DataSoft Solutions',
    logo: 'DS',
    category: 'IT & Software',
    status: 'suspended',
    rating: 3.1,
    joinedDate: '2024-05-18',
    location: 'Seattle, WA',
  },
]

// ── Recent RFQs Table ─────────────────────────────────────────────────────────
export const recentRfqsData = [
  {
    id: 'rfq-001',
    number: 'RFQ-2024-0847',
    title: 'Industrial Sensors — 500 Units',
    vendor: 'TechSupply Co.',
    status: 'open',
    deadline: '2024-08-20',
    budget: 75000,
    responses: 3,
  },
  {
    id: 'rfq-002',
    number: 'RFQ-2024-0846',
    title: 'Steel Brackets — Bulk Order',
    vendor: 'Global Materials Inc.',
    status: 'reviewing',
    deadline: '2024-08-18',
    budget: 42000,
    responses: 5,
  },
  {
    id: 'rfq-003',
    number: 'RFQ-2024-0845',
    title: 'Network Switches — 20 Units',
    vendor: 'DataSoft Solutions',
    status: 'awarded',
    deadline: '2024-08-15',
    budget: 28000,
    responses: 4,
  },
  {
    id: 'rfq-004',
    number: 'RFQ-2024-0844',
    title: 'Office Furniture Set',
    vendor: 'ProServices Group',
    status: 'open',
    deadline: '2024-08-22',
    budget: 18500,
    responses: 2,
  },
  {
    id: 'rfq-005',
    number: 'RFQ-2024-0843',
    title: 'Logistics — Q3 Freight',
    vendor: 'Swift Logistics',
    status: 'closed',
    deadline: '2024-08-10',
    budget: 95000,
    responses: 6,
  },
]

// ── Purchase Orders Table ─────────────────────────────────────────────────────
export const recentPurchaseOrdersData = [
  {
    id: 'po-001',
    number: 'PO-2024-1123',
    vendor: 'ElectroComponents Ltd.',
    description: 'Circuit Boards — 1,000 Units',
    amount: 48500,
    status: 'approved',
    dueDate: '2024-08-25',
    createdDate: '2024-08-01',
  },
  {
    id: 'po-002',
    number: 'PO-2024-1122',
    vendor: 'TechSupply Co.',
    description: 'Server RAM Modules — 50 Units',
    amount: 32750,
    status: 'pending',
    dueDate: '2024-08-30',
    createdDate: '2024-08-03',
  },
  {
    id: 'po-003',
    number: 'PO-2024-1121',
    vendor: 'Global Materials Inc.',
    description: 'Aluminum Sheets — 2 Tons',
    amount: 21800,
    status: 'delivered',
    dueDate: '2024-08-12',
    createdDate: '2024-07-28',
  },
  {
    id: 'po-004',
    number: 'PO-2024-1120',
    vendor: 'Swift Logistics',
    description: 'Freight Services — West Coast',
    amount: 15600,
    status: 'cancelled',
    dueDate: '2024-08-08',
    createdDate: '2024-07-25',
  },
  {
    id: 'po-005',
    number: 'PO-2024-1119',
    vendor: 'ProServices Group',
    description: 'IT Support Contract — Q3',
    amount: 60000,
    status: 'approved',
    dueDate: '2024-09-01',
    createdDate: '2024-08-05',
  },
]

// ── Notifications ─────────────────────────────────────────────────────────────
export const notificationsData = [
  {
    id: 'notif-1',
    type: 'approval',
    title: 'RFQ awaiting approval',
    description: 'RFQ-2024-0847 from TechSupply Co. needs your review.',
    time: '5 minutes ago',
    read: false,
    icon: 'FileText',
    color: 'blue',
  },
  {
    id: 'notif-2',
    type: 'verification',
    title: 'Vendor verification pending',
    description: 'Swift Logistics has completed onboarding. Verify now.',
    time: '1 hour ago',
    read: false,
    icon: 'Building2',
    color: 'purple',
  },
  {
    id: 'notif-3',
    type: 'inventory',
    title: 'Low inventory warning',
    description: '3 items have fallen below the minimum reorder threshold.',
    time: '2 hours ago',
    read: false,
    icon: 'Package',
    color: 'orange',
  },
  {
    id: 'notif-4',
    type: 'payment',
    title: 'Payment reminder',
    description: 'Invoice #INV-8820 from ElectroComponents is due in 2 days.',
    time: '4 hours ago',
    read: true,
    icon: 'CreditCard',
    color: 'green',
  },
  {
    id: 'notif-5',
    type: 'alert',
    title: 'Purchase order overdue',
    description: 'PO-2024-1118 delivery is 3 days past the expected date.',
    time: '6 hours ago',
    read: true,
    icon: 'AlertTriangle',
    color: 'red',
  },
]

// ── Calendar Events ───────────────────────────────────────────────────────────
export const calendarEventsData = [
  {
    id: 'cal-1',
    title: 'RFQ-0847 Deadline',
    date: '2024-08-20',
    type: 'rfq',
    color: 'blue',
  },
  {
    id: 'cal-2',
    title: 'PO-1123 Delivery',
    date: '2024-08-25',
    type: 'delivery',
    color: 'green',
  },
  {
    id: 'cal-3',
    title: 'Vendor Review Meeting',
    date: '2024-08-14',
    type: 'meeting',
    color: 'purple',
  },
  {
    id: 'cal-4',
    title: 'PO-1122 Due',
    date: '2024-08-30',
    type: 'po',
    color: 'orange',
  },
  {
    id: 'cal-5',
    title: 'Invoice INV-8841 Due',
    date: '2024-08-16',
    type: 'payment',
    color: 'cyan',
  },
  {
    id: 'cal-6',
    title: 'Quarterly Budget Review',
    date: '2024-08-28',
    type: 'meeting',
    color: 'purple',
  },
]
