import { createClient } from '@/lib/supabase/server'
import type {
  Invoice,
  InvoiceSummary,
  InvoiceFormData,
  InvoiceFilters,
  InvoiceListResult,
  InvoiceStats,
  Payment,
  PaymentFormData,
  PaymentListResult,
  PaymentFilters,
  VendorBalance,
  AgingReport,
} from '@/types/invoice'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function db() {
  return (await createClient()) as unknown as {
    from: (table: string) => any
    rpc: (fn: string, args?: any) => any
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// SELECT fragments
// ─────────────────────────────────────────────────────────────────────────────

const INVOICE_SUMMARY_SELECT = `
  id, invoice_number, invoice_date, due_date, status,
  subtotal, tax_amount, discount_amount, total_amount, paid_amount, remaining_amount,
  currency, created_at, updated_at, vendor_id, purchase_order_id,
  vendor:vendors ( id, name ),
  purchase_order:purchase_orders ( id, po_number )
`

const INVOICE_DETAIL_SELECT = `
  *,
  vendor:vendors ( id, name, email, status ),
  purchase_order:purchase_orders ( id, po_number ),
  items:invoice_items (
    *,
    product:products ( id, name, sku, unit )
  ),
  payments (
    *,
    created_by_user:users ( id, full_name, email )
  )
`

// ─────────────────────────────────────────────────────────────────────────────
// INVOICES — CRUD
// ─────────────────────────────────────────────────────────────────────────────

export async function getInvoices(
  companyId: string,
  filters: InvoiceFilters = {},
): Promise<InvoiceListResult> {
  const supabase = await db()
  const { search, status, vendor_id, overdue, page = 1, pageSize = 20 } = filters
  const from = (page - 1) * pageSize
  const to = from + pageSize - 1

  let query = supabase
    .from('invoices')
    .select(INVOICE_SUMMARY_SELECT, { count: 'exact' })
    .eq('company_id', companyId)
    .order('created_at', { ascending: false })
    .range(from, to)

  if (status) query = query.eq('status', status)
  if (vendor_id) query = query.eq('vendor_id', vendor_id)
  if (search) query = query.ilike('invoice_number', `%${search}%`)
  if (overdue) {
    const today = new Date().toISOString().slice(0, 10)
    query = query
      .lt('due_date', today)
      .not('status', 'in', '("paid","cancelled")')
  }

  const { data, error, count } = await query
  if (error) throw error

  return {
    data: (data ?? []) as InvoiceSummary[],
    total: count ?? 0,
    page,
    pageSize,
    hasNextPage: (count ?? 0) > to + 1,
  }
}

export async function getInvoiceById(
  id: string,
  companyId: string,
): Promise<Invoice | null> {
  const supabase = await db()
  const { data, error } = await supabase
    .from('invoices')
    .select(INVOICE_DETAIL_SELECT)
    .eq('id', id)
    .eq('company_id', companyId)
    .single()

  if (error) {
    if (error.code === 'PGRST116') return null
    throw error
  }

  // Sort items and payments by created_at
  if (data?.items) {
    data.items.sort(
      (a: { created_at: string }, b: { created_at: string }) =>
        new Date(a.created_at).getTime() - new Date(b.created_at).getTime(),
    )
  }
  if (data?.payments) {
    data.payments.sort(
      (a: { payment_date: string }, b: { payment_date: string }) =>
        new Date(b.payment_date).getTime() - new Date(a.payment_date).getTime(),
    )
  }

  return data as Invoice
}

export async function createInvoice(
  companyId: string,
  createdBy: string,
  data: InvoiceFormData,
): Promise<Invoice> {
  const supabase = await db()

  const { items, ...fields } = data

  // invoice_number is auto-generated by DB trigger (pass empty string)
  const { data: invoice, error } = await supabase
    .from('invoices')
    .insert({
      company_id: companyId,
      created_by: createdBy,
      invoice_number: '',
      purchase_order_id: fields.purchase_order_id ?? null,
      vendor_id: fields.vendor_id,
      invoice_date: fields.invoice_date,
      due_date: fields.due_date ?? null,
      discount_amount: fields.discount_amount ?? 0,
      currency: fields.currency ?? 'INR',
      notes: fields.notes ?? null,
      status: 'draft',
    })
    .select()
    .single()

  if (error) throw error

  if (items && items.length > 0) {
    const itemRows = items.map((item) => ({
      invoice_id: invoice.id,
      product_id: item.product_id ?? null,
      description: item.description,
      quantity: item.quantity,
      unit_price: item.unit_price,
      tax_percentage: item.tax_percentage ?? 0,
    }))
    const { error: itemsErr } = await supabase.from('invoice_items').insert(itemRows)
    if (itemsErr) throw itemsErr
  }

  const created = await getInvoiceById(invoice.id, companyId)
  return created as Invoice
}

export async function updateInvoice(
  id: string,
  companyId: string,
  data: Partial<InvoiceFormData>,
): Promise<Invoice> {
  const supabase = await db()
  const { items, ...fields } = data

  const nullable = ['purchase_order_id', 'due_date', 'notes'] as const
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const sanitized: Record<string, any> = { ...fields }
  for (const key of nullable) {
    if (key in sanitized && (sanitized[key] === '' || sanitized[key] === undefined)) {
      sanitized[key] = null
    }
  }

  const { error } = await supabase
    .from('invoices')
    .update({ ...sanitized, updated_at: new Date().toISOString() })
    .eq('id', id)
    .eq('company_id', companyId)
  if (error) throw error

  // Replace items if provided
  if (items !== undefined) {
    const { error: delErr } = await supabase
      .from('invoice_items')
      .delete()
      .eq('invoice_id', id)
    if (delErr) throw delErr

    if (items.length > 0) {
      const itemRows = items.map((item) => ({
        invoice_id: id,
        product_id: item.product_id ?? null,
        description: item.description,
        quantity: item.quantity,
        unit_price: item.unit_price,
        tax_percentage: item.tax_percentage ?? 0,
      }))
      const { error: itemsErr } = await supabase.from('invoice_items').insert(itemRows)
      if (itemsErr) throw itemsErr
    }
  }

  const updated = await getInvoiceById(id, companyId)
  return updated as Invoice
}

export async function updateInvoiceStatus(
  id: string,
  companyId: string,
  status: 'submitted' | 'approved' | 'cancelled',
): Promise<void> {
  const supabase = await db()
  const { error } = await supabase
    .from('invoices')
    .update({ status, updated_at: new Date().toISOString() })
    .eq('id', id)
    .eq('company_id', companyId)
  if (error) throw error
}

export async function deleteInvoice(id: string, companyId: string): Promise<void> {
  const supabase = await db()
  // Only allow deleting draft invoices
  const { error } = await supabase
    .from('invoices')
    .delete()
    .eq('id', id)
    .eq('company_id', companyId)
    .eq('status', 'draft')
  if (error) throw error
}

// ─────────────────────────────────────────────────────────────────────────────
// PAYMENTS
// ─────────────────────────────────────────────────────────────────────────────

export async function recordPayment(
  companyId: string,
  createdBy: string,
  data: PaymentFormData,
): Promise<Payment> {
  const supabase = await db()

  // Validate: cannot over-pay
  const { data: inv } = await supabase
    .from('invoices')
    .select('remaining_amount, status, vendor_id')
    .eq('id', data.invoice_id)
    .eq('company_id', companyId)
    .single()

  if (!inv) throw new Error('Invoice not found')
  if (inv.status === 'paid') throw new Error('Invoice is already fully paid')
  if (inv.status === 'cancelled') throw new Error('Cannot pay a cancelled invoice')
  if (inv.status === 'draft') throw new Error('Invoice must be approved before payment')
  if (inv.status === 'submitted') throw new Error('Invoice must be approved before payment')
  if (data.amount > inv.remaining_amount + 0.01) {
    throw new Error(
      `Payment amount (${data.amount}) exceeds remaining balance (${inv.remaining_amount})`,
    )
  }

  // payment_reference auto-generated by DB trigger (pass empty string)
  const { data: payment, error } = await supabase
    .from('payments')
    .insert({
      invoice_id: data.invoice_id,
      company_id: companyId,
      vendor_id: inv.vendor_id,
      payment_reference: '',
      payment_date: data.payment_date,
      payment_method: data.payment_method,
      amount: data.amount,
      notes: data.notes ?? null,
      created_by: createdBy,
    })
    .select()
    .single()

  if (error) throw error
  return payment as Payment
}

export async function getPayments(
  companyId: string,
  filters: PaymentFilters = {},
): Promise<PaymentListResult> {
  const supabase = await db()
  const { vendor_id, invoice_id, payment_method, from_date, to_date, page = 1, pageSize = 30 } = filters
  const from = (page - 1) * pageSize
  const to = from + pageSize - 1

  let query = supabase
    .from('payments')
    .select(
      `*,
       vendor:vendors ( id, name ),
       invoice:invoices ( id, invoice_number, total_amount ),
       created_by_user:users ( id, full_name, email )`,
      { count: 'exact' },
    )
    .eq('company_id', companyId)
    .order('payment_date', { ascending: false })
    .order('created_at', { ascending: false })
    .range(from, to)

  if (vendor_id) query = query.eq('vendor_id', vendor_id)
  if (invoice_id) query = query.eq('invoice_id', invoice_id)
  if (payment_method) query = query.eq('payment_method', payment_method)
  if (from_date) query = query.gte('payment_date', from_date)
  if (to_date) query = query.lte('payment_date', to_date)

  const { data, error, count } = await query
  if (error) throw error

  return {
    data: (data ?? []) as Payment[],
    total: count ?? 0,
    page,
    pageSize,
    hasNextPage: (count ?? 0) > to + 1,
  }
}

export async function getPaymentById(id: string, companyId: string): Promise<Payment | null> {
  const supabase = await db()
  const { data, error } = await supabase
    .from('payments')
    .select(
      `*,
       vendor:vendors ( id, name ),
       invoice:invoices ( id, invoice_number, total_amount ),
       created_by_user:users ( id, full_name, email )`,
    )
    .eq('id', id)
    .eq('company_id', companyId)
    .single()

  if (error) {
    if (error.code === 'PGRST116') return null
    throw error
  }
  return data as Payment
}

// ─────────────────────────────────────────────────────────────────────────────
// STATS & DASHBOARD
// ─────────────────────────────────────────────────────────────────────────────

export async function getInvoiceStats(companyId: string): Promise<InvoiceStats> {
  const supabase = await db()
  const today = new Date().toISOString().slice(0, 10)
  const monthStart = today.slice(0, 7) + '-01'

  const [totalResult, pendingResult, overdueResult, outstandingResult, paidMonthResult, todayResult] =
    await Promise.all([
      supabase
        .from('invoices')
        .select('id', { count: 'exact', head: true })
        .eq('company_id', companyId),

      supabase
        .from('invoices')
        .select('id', { count: 'exact', head: true })
        .eq('company_id', companyId)
        .eq('status', 'submitted'),

      supabase
        .from('invoices')
        .select('id', { count: 'exact', head: true })
        .eq('company_id', companyId)
        .lt('due_date', today)
        .not('status', 'in', '("paid","cancelled","draft")'),

      supabase
        .from('invoices')
        .select('remaining_amount')
        .eq('company_id', companyId)
        .in('status', ['approved', 'partially_paid']),

      supabase
        .from('payments')
        .select('amount')
        .eq('company_id', companyId)
        .gte('payment_date', monthStart),

      supabase
        .from('payments')
        .select('amount')
        .eq('company_id', companyId)
        .eq('payment_date', today),
    ])

  const outstanding = (outstandingResult.data ?? []).reduce(
    (s: number, r: { remaining_amount: number }) => s + (r.remaining_amount ?? 0),
    0,
  )
  const paidMonth = (paidMonthResult.data ?? []).reduce(
    (s: number, r: { amount: number }) => s + (r.amount ?? 0),
    0,
  )
  const todayPaid = (todayResult.data ?? []).reduce(
    (s: number, r: { amount: number }) => s + (r.amount ?? 0),
    0,
  )

  return {
    total_invoices: totalResult.count ?? 0,
    pending_approval: pendingResult.count ?? 0,
    outstanding_amount: outstanding,
    paid_this_month: paidMonth,
    overdue_count: overdueResult.count ?? 0,
    todays_payments: todayPaid,
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// VENDOR BALANCES
// ─────────────────────────────────────────────────────────────────────────────

export async function getVendorBalances(
  companyId: string,
  page = 1,
  pageSize = 20,
): Promise<{ data: VendorBalance[]; total: number }> {
  const supabase = await db()
  const today = new Date().toISOString().slice(0, 10)

  // Fetch all non-cancelled, non-draft invoices with vendor info
  const { data, error } = await supabase
    .from('invoices')
    .select(
      `vendor_id, total_amount, paid_amount, remaining_amount, due_date,
       vendor:vendors ( id, name )`,
    )
    .eq('company_id', companyId)
    .not('status', 'in', '("cancelled","draft")')

  if (error) throw error

  // Aggregate by vendor
  const map = new Map<
    string,
    {
      vendor_id: string
      vendor_name: string
      total_invoiced: number
      total_paid: number
      outstanding: number
      overdue_amount: number
      invoice_count: number
      oldest_due_date: string | null
    }
  >()

  for (const row of data ?? []) {
    const vid = row.vendor_id
    const existing = map.get(vid) ?? {
      vendor_id: vid,
      vendor_name: (row.vendor as { name: string } | null)?.name ?? '—',
      total_invoiced: 0,
      total_paid: 0,
      outstanding: 0,
      overdue_amount: 0,
      invoice_count: 0,
      oldest_due_date: null,
    }
    existing.total_invoiced += row.total_amount ?? 0
    existing.total_paid += row.paid_amount ?? 0
    existing.outstanding += row.remaining_amount ?? 0
    existing.invoice_count += 1
    if (row.remaining_amount > 0 && row.due_date && row.due_date < today) {
      existing.overdue_amount += row.remaining_amount ?? 0
    }
    if (
      row.due_date &&
      (!existing.oldest_due_date || row.due_date < existing.oldest_due_date)
    ) {
      existing.oldest_due_date = row.due_date
    }
    map.set(vid, existing)
  }

  const all = Array.from(map.values()).sort((a, b) => b.outstanding - a.outstanding)
  const paged = all.slice((page - 1) * pageSize, page * pageSize)

  return { data: paged as VendorBalance[], total: all.length }
}

// ─────────────────────────────────────────────────────────────────────────────
// AGING REPORT
// ─────────────────────────────────────────────────────────────────────────────

export async function getAgingReport(companyId: string): Promise<AgingReport> {
  const supabase = await db()
  const today = new Date()
  const todayStr = today.toISOString().slice(0, 10)

  const { data, error } = await supabase
    .from('invoices')
    .select('remaining_amount, due_date')
    .eq('company_id', companyId)
    .in('status', ['approved', 'partially_paid'])
    .gt('remaining_amount', 0)

  if (error) throw error

  const report: AgingReport = {
    current: { label: 'Current', count: 0, amount: 0 },
    days_1_30: { label: '1–30 days', count: 0, amount: 0 },
    days_31_60: { label: '31–60 days', count: 0, amount: 0 },
    days_61_90: { label: '61–90 days', count: 0, amount: 0 },
    over_90: { label: '90+ days', count: 0, amount: 0 },
  }

  for (const row of data ?? []) {
    const amt = row.remaining_amount ?? 0
    if (!row.due_date || row.due_date >= todayStr) {
      report.current.count++
      report.current.amount += amt
    } else {
      const diffMs = today.getTime() - new Date(row.due_date).getTime()
      const days = Math.floor(diffMs / 86400000)
      if (days <= 30) {
        report.days_1_30.count++
        report.days_1_30.amount += amt
      } else if (days <= 60) {
        report.days_31_60.count++
        report.days_31_60.amount += amt
      } else if (days <= 90) {
        report.days_61_90.count++
        report.days_61_90.amount += amt
      } else {
        report.over_90.count++
        report.over_90.amount += amt
      }
    }
  }

  return report
}

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS — dropdown data
// ─────────────────────────────────────────────────────────────────────────────

export async function getApprovedPurchaseOrders(
  companyId: string,
): Promise<Array<{ id: string; po_number: string; vendor_id: string; vendor: { name: string } | null }>> {
  const supabase = await db()
  const { data, error } = await supabase
    .from('purchase_orders')
    .select('id, po_number, vendor_id, vendor:vendors ( name )')
    .eq('company_id', companyId)
    .in('status', ['approved', 'sent', 'acknowledged', 'in_progress', 'completed'])
    .order('created_at', { ascending: false })
    .limit(200)
  if (error) throw error
  return (data ?? []) as Array<{
    id: string
    po_number: string
    vendor_id: string
    vendor: { name: string } | null
  }>
}

export async function getActiveVendors(
  companyId: string,
): Promise<Array<{ id: string; name: string }>> {
  const supabase = await db()
  const { data, error } = await supabase
    .from('vendors')
    .select('id, name')
    .eq('company_id', companyId)
    .eq('status', 'active')
    .order('name')
    .limit(300)
  if (error) throw error
  return (data ?? []) as Array<{ id: string; name: string }>
}

export async function getActiveProducts(
  companyId: string,
): Promise<Array<{ id: string; name: string; sku: string; unit: string; unit_cost: number }>> {
  const supabase = await db()
  const { data, error } = await supabase
    .from('products')
    .select('id, name, sku, unit, unit_cost')
    .eq('company_id', companyId)
    .eq('status', 'active')
    .order('name')
    .limit(300)
  if (error) throw error
  return (data ?? []) as Array<{ id: string; name: string; sku: string; unit: string; unit_cost: number }>
}
